### ISSUE TITLE
CachingEnumerable behaviour

### ISSUE THREAD

**Issue by ammachado** [ayende/rhino-etl#3]
How should CachingEnumerable in this situation?

    [Fact]
    public void Calling_FirstOrDefault_In_CachingEnumerable_Behaviour()
    {
        var rows = new CachingEnumerable<Row>(GetRows());
        var row = rows.FirstOrDefault();
        Assert.NotNull(row);
    
        var rowCount = rows.Count();
        Assert.Equal(2, rowCount);
    }
    
    private static IEnumerable<Row> GetRows()
    {
        var firstRow = new Row();
        first["field"] = "first";
        yield return firstRow;
    
        var secondRow = new Row();
        first["field"] = "second";
        yield return secondRow;
    }

**Comment by regisbsb** [comment]
@ammachado https://github.com/hibernating-rhinos/rhino-etl
